name: publish site
on:
  push:
    branches: [ master ]  # 改成你的分支名 master
  pull_request:
    branches: [ master ]  # 改成你的分支名 master
  workflow_dispatch:      # 新增这一行，开启手动触发
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material # 使用pip包管理工具安装mkdocs-material
      - run: mkdocs gh-deploy --force # 使用mkdocs-material部署gh-pages分支